#!/usr/bin/env bash
# print Best School 10 times and Hi on the 9th

count=1
while (( count<=10 )); do

      echo "Best School"

      if (( count == 9 )); then
	 echo "Hi"
	fi
	
      (( count++ ))
done