#!/usr/bin/env bash
# print bad luck for 4, good luck for 8, else Best School

count=1
while (( count<=10 )); do

      if (( count == 4 )); then
      	 echo "bad luck"

      elif (( count == 8 )); then
      	   echo "good luck"
      else
	echo "Best School"
      fi

	(( count++ ))
done
